### PR TITLE
Adding new custom attributes that we use internally

### PR DESCRIPTION
**Pull request by jbaker10**
Includes one to return the active IP address (useful when a machine is on a VPN), SSH version, OpenSSL version, local admin accounts on a machine, and a machines local hostname.

### CODE REVIEW

**Comment by menelson** [comment]
@jbaker10  Thanks for these updates. Once you amend your commit message to include the DCO (Developer Certificate of Origin), I'll merge the request.

[How to amend commit](https://help.github.com/articles/changing-a-commit-message/)

**Comment by jbaker10** [comment]
Hi @menelson I added the DCO for each commit and squashed them into 1. Does that work?

**Comment by jbaker10** [comment]
Gentle bump on this PR

**Comment by rterakedis** [comment]
Thanks for the contribution @jbaker10!!

**Pull request merged**
